import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "@/shared/ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const jetBrainsMonoRegular = localFont({
  src: "./fonts/JetBrainsMono/JetBrainsMono-Regular.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMonoRegular.className} antialiased bg-bgPrimary text-textPrimary`}
      >
        <ReactQueryProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
